language: node_js

node_js:
  - node
  
os:
  - osx

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
  
before_install:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"
  - echo "Disregard the previous message about adding specs."

before_script:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      if [ "${ATOM_CHANNEL}" = "stable" ] || [ "${ATOM_CHANNEL}" = "dev" ]; then
        export ATOM_SCRIPT_NAME="atom"
        export APM_SCRIPT_NAME="apm"
      else
        export ATOM_SCRIPT_NAME="atom-${ATOM_CHANNEL}"
        export APM_SCRIPT_NAME="apm-${ATOM_CHANNEL}"
      fi
      
      export PATH=${PATH}:${HOME}/atom/usr/bin
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
      if [ "${ATOM_CHANNEL}" = "stable" ] || [ "${ATOM_CHANNEL}" = "dev" ]; then
        export ATOM_APP_NAME="Atom.app"
      else
        export ATOM_APP_NAME="Atom ${ATOM_CHANNEL}.app"
      fi
      
      ln -s "$PWD/atom/${ATOM_APP_NAME}/Contents/Resources/app/atom.sh" "$PWD/atom/atom"
      export PATH=$PATH:$PWD/atom
      export PATH=$PATH:$PWD/atom/$ATOM_APP_NAME/Contents/Resources/app/apm/node_modules/.bin
    fi