language: node_js

node_js:
  - node
  - lts/*
  
os:
  - osx
  - linux

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta
  
before_install:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - "./build-package.sh"
  - echo "Disregard the previous message about adding specs."
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      if [ "${ATOM_CHANNEL}" = "stable" ] || [ "${ATOM_CHANNEL}" = "dev" ]; then
        export ATOM_SCRIPT_NAME="atom"
        export APM_SCRIPT_NAME="apm"
      else
        export ATOM_SCRIPT_NAME="atom-${ATOM_CHANNEL}"
        export APM_SCRIPT_NAME="apm-${ATOM_CHANNEL}"
      fi
      
      export PATH=${PATH}:${HOME}/atom/usr/bin/
      ls ${HOME}/atom/usr/bin/
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then 
      if [ "${ATOM_CHANNEL}" = "stable" ] || [ "${ATOM_CHANNEL}" = "dev" ]; then
        export ATOM_APP_NAME="Atom.app"
        export ATOM_SCRIPT_NAME="atom.sh"
        export ATOM_SCRIPT_PATH="./atom/${ATOM_APP_NAME}/Contents/Resources/app/atom.sh"
      else
        export ATOM_APP_NAME="Atom ${ATOM_CHANNEL}.app"
        export ATOM_SCRIPT_NAME="atom-${ATOM_CHANNEL}"
        export ATOM_SCRIPT_PATH="./atom-${ATOM_CHANNEL}"
        ln -s "./atom/${ATOM_APP_NAME}/Contents/Resources/app/atom.sh" "${ATOM_SCRIPT_PATH}"
      fi
      
      export PATH=${PATH}:./atom/${ATOM_APP_NAME}/Contents/Resources/app/
      ls ./atom/${ATOM_APP_NAME}/Contents/Resources/app/
      export PATH=${PATH}:./atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/node_modules/.bin/
      ls ./atom/${ATOM_APP_NAME}/Contents/Resources/app/apm/node_modules/.bin/
    fi
  - echo $PATH